import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LandingPage from './Landing/Landing'
import About from './Landing/About'
import Clients from './Landing/Clients'
import Testimonials from './Landing/Testmunials'
import Footer from './Landing/Footer'
import Contact from './Landing/Contact'
import Projects from './Landing/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Agency CostaWeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LandingPage />
        <About />
        <Projects />
        <Clients />
        <Testimonials />
        <Contact />
        <Footer />
      </main>
    </>
  )
}
